.\" -*- nroff -*-
.TH revnetgroup 8 "March 2001" "YP Server"
.SH NAME
revnetgroup - generate reverse netgroup data
.SH SYNOPSIS
.B @YPBINDIR@/revnetgroup \-u|\-h 
.SH DESCRIPTION
.B revnetgroup
processes the contents of a  netgroup file into a reverse netgroup form.
.LP
.SH OPTIONS
.TP
.B \-u
Generate netgroup.byuser output
.TP
.B \-h
Generate netgroup.byhost outpout
.TP
revnetgroup reads the data from the standard input. 
.SH FILES
/etc/netgroup
.TP
@YPMAPDIR@/Makefile
.SH "SEE ALSO"
.BR makedbm (8),
.BR ypserv (8)
.SH AUTHOR
Thorsten Kukuk <kukuk@suse.de>
