.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "NETGROUP" "5" "04/06/2006" "NIS Reference Manual" "NIS Reference Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
netgroup \- specify network groups
.SH "DESCRIPTION"
.PP
The
\fInetgroup\fR
file defines "netgroups", which are sets of (host, user, domain) tuples, used for permission checking when doing remote mounts,remote logins and remote shells.
.PP
Each line in the file consists of a netgroup name followed by a by a list of members, where a member is either another netgroup name, or a triple:
.sp
.nf
   (\fIhost\fR, \fIuser\fR, \fIdomain\fR) 
.fi
.PP
where the
\fIhost\fR,
\fIuser\fR, and
\fIdomain\fR
are character strings for the corresponding components. Any of the three fields can be empty, in which case it specifies a "wildcard", or may consist of the string "\-" to specify "no valid value". The
\fIdomain\fR
field must either be the local domain name or empty for the netgroup entry to be used. This field does not limit the netgroup or provide security. The domain field refers to the domain in which the triple is valid, not the domain containing the the trusted host.
.PP
A gateway machine should be listed under all possible hostnames by which it may be recognized:
.sp
.nf
   gateway (server, , ) (server\-sn, , ) (server\-bb, , )
.fi
.PP
The
\fBgetnetgrent\fR(3), function should normally be used to access the netgroup database.
.SH "FILES"
.PP
\fI/etc/netgroup\fR
.SH "SEE ALSO"
.PP
\fBgetnetgrent\fR(3),
\fBexports\fR(5),
\fBmakedbm\fR(8),
\fBypserv\fR(8)
.SH "WARNINGS"
.PP
The triple (,,domain) allows all users and machines trusted access, and has the same effect as the triple (,,). Use the
\fIhost\fR
and
\fIuser\fR
fields of the triple to restrict the access correctly to a specific set of members.
.SH "AUTHOR"
.PP
Thorsten Kukuk <kukuk@thkukuk.de>
